### ISSUE TITLE
Support for RHEL

### ISSUE THREAD

**Issue by Dr-Crow** [marist-projects/ssh-honeypot#10]
We need to add an "enterprise" distro. It should not be a big port from centos to RHEL.

**Comment by Dr-Crow** [comment]
Added fix for dependency issue. Still need added support for OS detection.

**Comment by marcosb1** [comment]
NOTE: ``libssh-devel`` doesn't exist in Red Hat, or is called something else.

**Comment by marcosb1** [comment]
Fixed check 617b64ec518f6ad60d3ac93f75ddd97ed27a0870
