### ISSUE TITLE
Segfault errors following newest update

### ISSUE THREAD

**Issue by Dr-Crow** [marist-projects/ssh-honeypot#14]
Problem with logs coming in. Doesn't affect integrity of data, but would be nice to get this resolved.

``<6>1 2017-04-01T12:04:27.066548-04:00 AlbanyDebianHP01 kernel - - - [69885.500754] sshd-new[11442]: segfault at d1f7 ip 00007f861d60cdcc sp 00007ffcaef31f80 error 4 in libc-2.19.so[7f861d5c2000+1a1000]``

``<6>1 2017-04-01T12:04:49.198528-04:00 AlbanyDebianHP01 kernel - - - [69907.612715] sshd-new[11450]: segfault at 6510 ip 00007f2f89922dcc sp 00007fffaf16a7d0 error 4 in libc-2.19.so[7f2f898d8000+1a1000]``

**Comment by marcosb1** [comment]
No way to replicate error. We think that it has to do with a ``lib.c`` function. The only two ``lib.c`` functions being used are ``log2()`` and ``getenv()``. The ``segfault`` error appears when there is a ``NULL`` argument for a function. We edited the ``log2()`` functions and we are no longer seeing this error. Will close this issue when we can replicate the problem. See [this](https://lists.debian.org/debian-glibc/2015/10/msg00086.html) for more details.

**Comment by Dr-Crow** [comment]
Monitored the solution for an hour. Have not seen any segfault errors. Closing the issue for now. Will continue the monitor for a couple days.
