### ISSUE TITLE
Ubuntu doesn't echo HPID

### ISSUE THREAD

**Issue by marcosb1** [marist-projects/ssh-honeypot#7]
Even after putting the environment variable in <code>/etc/environment</code>, after reboot, it still doesn't recognize <code>$HPID</code>. It displays in the logs however.

**Comment by Dr-Crow** [comment]
Does Minibian or Debian have this problem as well?

**Comment by marcosb1** [comment]
Incorrect issue. The real SSH had an issue starting up. Nothing to do with us.
