### ISSUE TITLE
Rsyslog Unexpected Crash

### ISSUE THREAD

**Issue by marcosb1** [marist-projects/ssh-honeypot#8]
Have a watchdog for ``rsyslog``. If it's not logging then restart the ``rsyslog`` process

**Comment by Dr-Crow** [comment]
![image](https://cloud.githubusercontent.com/assets/9339757/23228096/5b34f71a-f909-11e6-807a-b06f2f6459a6.png)


Error that rsyslog reported.

**Comment by Dr-Crow** [comment]
Could not reproduce.
